# Generated by Django 4.1.4 on 2022-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Detective', 'Детектив'), ('Horror', 'Хоррор'), ('Manga', 'Манга'), ('Comedy', 'Комедия'), ('Document', 'Документальный'), ('Fantastic', 'Фантастика')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
