# Generated by Django 4.1.4 on 2022-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Roman', 'Роман'), ('Detective', 'Детектив'), ('Horror', 'Хоррор'), ('Manga', 'Манга'), ('Comedy', 'Комедия'), ('Fantastic', 'Фантастика')], max_length=100),
        ),
    ]
